services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo_network
    healthcheck:  # DESCOMENTE O HEALTHCHECK DO MYSQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  flask-api:
    build: ./server_py  # ← CORRIJA A INDENTAÇÃO AQUI (2 espaços)
    container_name: todo_flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://todo_user:todo_password@mysql:3306/todo_app
    networks:
      - todo_network
    volumes:
      - ./server_py:/app
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c 'echo > /dev/tcp/localhost/5000' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  react-app:
    build: ./client
    container_name: todo_react
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      flask-api:
        condition: service_healthy
    environment:
      VITE_API_URL: http://localhost:5000
    networks:
      - todo_network
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  mysql_data:

networks:
  todo_network:
    driver: bridge